// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuk0Zzoe57ZPr9WKAHksmZedrjxrquQX4',
    appId: '1:284351881545:web:387f35a140de2f538b3a98',
    messagingSenderId: '284351881545',
    projectId: 'enthusias-e331f',
    authDomain: 'enthusias-e331f.firebaseapp.com',
    storageBucket: 'enthusias-e331f.appspot.com',
    measurementId: 'G-G9JRZ3NR9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiDPTs9Vuz2FMYrjsp8Bkji7xjhyOeHOs',
    appId: '1:284351881545:android:c943a61575ca079f8b3a98',
    messagingSenderId: '284351881545',
    projectId: 'enthusias-e331f',
    storageBucket: 'enthusias-e331f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHvVRgHSDBZgFXfM9Zehd5ePmJ8Q7aJ4',
    appId: '1:284351881545:ios:e948d120c23da58d8b3a98',
    messagingSenderId: '284351881545',
    projectId: 'enthusias-e331f',
    storageBucket: 'enthusias-e331f.appspot.com',
    iosBundleId: 'com.example.ton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHvVRgHSDBZgFXfM9Zehd5ePmJ8Q7aJ4',
    appId: '1:284351881545:ios:e948d120c23da58d8b3a98',
    messagingSenderId: '284351881545',
    projectId: 'enthusias-e331f',
    storageBucket: 'enthusias-e331f.appspot.com',
    iosBundleId: 'com.example.ton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuk0Zzoe57ZPr9WKAHksmZedrjxrquQX4',
    appId: '1:284351881545:web:f6ba61e795645b268b3a98',
    messagingSenderId: '284351881545',
    projectId: 'enthusias-e331f',
    authDomain: 'enthusias-e331f.firebaseapp.com',
    storageBucket: 'enthusias-e331f.appspot.com',
    measurementId: 'G-M824V31WDK',
  );
}
